graph TD
    n-src-redesign-7f09db["redesign\nsrc/redesign"]
    n-src-animated-demo-assets-mjs-ba0181["animated-demo-assets.mjs\nsrc/animated-demo-assets.mjs"]
    n-src-copy-mjs-3ba769["copy.mjs\nsrc/copy.mjs"]
    n-src-fifteen-second-films-mjs-025941["fifteen-second-films.mjs\nsrc/fifteen-second-films.mjs"]
    n-src-films-mjs-80998b["films.mjs\nsrc/films.mjs"]
    n-src-genie-lp-mjs-1a3bc0["genie-lp.mjs\nsrc/genie-lp.mjs"]
    n-src-home-flagship-mjs-18095a["home-flagship.mjs\nsrc/home-flagship.mjs"]
    n-src-home-task-picker-mjs-997852["home-task-picker.mjs\nsrc/home-task-picker.mjs"]
