import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import{IDS}from'../public/assets/lab-core.mjs';import{createDraft,exportDraft}from'../public/assets/sample-draft.mjs';import{createDraftReopen,operationText}from'../public/assets/draft-operation.mjs';
const bytes=(product='genie',language='en',text='New text')=>new TextEncoder().encode(exportDraft(createDraft({product,language,text})).text);
const file=data=>({size:data.length,arrayBuffer:async()=>data.buffer});
function env(){const drafts=new Map([['genie','Original']]),states=[];return {drafts,states,controller:createDraftReopen({apply:d=>drafts.set(d.product,d.text),readback:p=>drafts.get(p),onState:s=>states.push(s.phase)})};}
for(const product of IDS)for(const language of['ja','en'])test(`real reopen adopts event contract: ${product}/${language}`,async()=>{const e=env();const r=await e.controller.open(file(bytes(product,language)),{product,language});assert.equal(r.status,'done');assert.equal(e.drafts.get(product),'New text');assert.deepEqual(e.states,['idle','review','running','verifying','done']);assert.equal(r.state.evidence.verified,true);});
test('pending read stays running; elapsed time cannot make it done',async()=>{const e=env();let resolve;const task=e.controller.open({size:100,arrayBuffer:()=>new Promise(r=>resolve=r)},{product:'genie',language:'en'});await Promise.resolve();assert.equal(e.controller.state().phase,'running');assert.equal(e.drafts.get('genie'),'Original');resolve(bytes().buffer);await task;assert.equal(e.controller.state().phase,'done');});
test('cancelled read ignores delayed bytes and cannot apply or succeed',async()=>{const e=env();let resolve;const task=e.controller.open({size:100,arrayBuffer:()=>new Promise(r=>resolve=r)},{product:'genie',language:'en'});e.controller.cancel();resolve(bytes().buffer);assert.equal((await task).status,'cancelled');assert.equal(e.controller.state().phase,'cancelled');assert.equal(e.drafts.get('genie'),'Original');assert.ok(!e.states.includes('done'));});
test('a newer reopen wins even if the old read resolves later',async()=>{const e=env();let resolve;const old=e.controller.open({size:100,arrayBuffer:()=>new Promise(r=>resolve=r)},{product:'genie',language:'en'});await e.controller.open(file(bytes('genie','en','Fresh')),{product:'genie',language:'en'});resolve(bytes('genie','en','Old').buffer);assert.equal((await old).status,'cancelled');assert.equal(e.drafts.get('genie'),'Fresh');assert.equal(e.controller.state().phase,'done');});
test('edited or switched product invalidates the pending read',async()=>{const e=env();let resolve,valid=true;const task=e.controller.open({size:100,arrayBuffer:()=>new Promise(r=>resolve=r)},{product:'genie',language:'en',isCurrent:()=>valid});valid=false;resolve(bytes().buffer);assert.equal((await task).status,'cancelled');assert.equal(e.drafts.get('genie'),'Original');assert.equal(e.controller.state().phase,'cancelled');});
for(const[reason,f]of[['too large',{size:32769,arrayBuffer:async()=>{throw Error('must not read')}}],['wrong product',file(bytes('oathra'))],['wrong language',file(bytes('genie','ja'))],['malformed',file(new Uint8Array([0xff]))],['read rejected',{size:10,arrayBuffer:async()=>{throw Error('denied')}}]])test(`${reason}: no application or success`,async()=>{const e=env();const r=await e.controller.open(f,{product:'genie',language:'en'});assert.equal(r.status,'error');assert.equal(e.controller.state().phase,'error');assert.equal(e.drafts.get('genie'),'Original');assert.ok(!e.states.includes('done'));});
test('failed read-back cannot be reported as done',async()=>{const states=[];const c=createDraftReopen({apply:()=>{},readback:()=>undefined,onState:s=>states.push(s.phase)});const r=await c.open(file(bytes()),{product:'genie',language:'en'});assert.equal(r.status,'error');assert.equal(r.error.code,'APPLY_MISMATCH');assert.deepEqual(states,['idle','review','running','verifying','error']);});
test('new edits reset prior evidence; translations are not success assumptions',async()=>{const e=env();await e.controller.open(file(bytes()),{product:'genie',language:'en'});e.controller.reset();assert.equal(e.controller.state(),null);assert.equal(e.states.at(-1),'idle');assert.match(operationText({phase:'done'},'ja'),/確認済み/);assert.doesNotMatch(operationText({phase:'running'}),/saved|done/i);});
test('integrated entrypoint uses shared reducer, stable status, and keeps download unverified',async()=>{const ui=await fs.readFile(new URL('../public/assets/lab-explorer.mjs',import.meta.url),'utf8');const op=await fs.readFile(new URL('../public/assets/draft-operation.mjs',import.meta.url),'utf8');assert.match(ui,/reopen\.open\(file/);assert.match(ui,/box\.append\(operationStatus,operationContent\)/);assert.match(ui,/operationContent\.innerHTML=/);assert.doesNotMatch(ui,/box\.innerHTML=/);assert.match(ui,/Download requested\. Check the file/);assert.match(op,/from '\.\/motion-contract\.mjs'/);assert.doesNotMatch(op,/setTimeout|setInterval|requestAnimationFrame|CUES|phaseAt|elapsed/);});

test('invalidated read rejection settles the state as cancelled',async()=>{const e=env();let reject,valid=true;const task=e.controller.open({size:100,arrayBuffer:()=>new Promise((_,r)=>reject=r)},{product:'genie',language:'en',isCurrent:()=>valid});valid=false;reject(Error('read failed after editing'));assert.equal((await task).status,'cancelled');assert.equal(e.controller.state().phase,'cancelled');assert.equal(e.drafts.get('genie'),'Original');});
test('synchronous cancellation inside apply never returns done',async()=>{let c;const seen=[];c=createDraftReopen({apply:()=>c.cancel(),readback:()=> 'New text',onState:s=>seen.push(s.phase)});const r=await c.open(file(bytes()),{product:'genie',language:'en'});assert.equal(r.status,'cancelled');assert.equal(c.state().phase,'cancelled');assert.ok(!seen.includes('done'));});
test('cancellation from verifying notification blocks applying the file',async()=>{let c,applied=false;c=createDraftReopen({apply:()=>{applied=true},readback:()=> 'New text',onState:s=>{if(s.phase==='verifying')c.cancel()}});const r=await c.open(file(bytes()),{product:'genie',language:'en'});assert.equal(r.status,'cancelled');assert.equal(applied,false);assert.equal(c.state().phase,'cancelled');});

test('reentrant retry cannot redirect old cancellation into a new operation',async()=>{let c,resolve,retry;const values=new Map();c=createDraftReopen({apply:d=>values.set(d.product,d.text),readback:p=>values.get(p),onState:s=>{if(s.cancelRequested&&!retry)retry=c.open(file(bytes('genie','en','Newest')),{product:'genie',language:'en'});}});const old=c.open({size:100,arrayBuffer:()=>new Promise(r=>resolve=r)},{product:'genie',language:'en'});c.cancel();resolve(bytes('genie','en','Old').buffer);assert.equal((await old).status,'cancelled');assert.equal((await retry).status,'done');assert.equal(c.state().phase,'done');assert.equal(values.get('genie'),'Newest');});

test('initially invalid context is cancelled before IO',async()=>{const e=env();let read=false;const r=await e.controller.open({size:100,arrayBuffer:async()=>{read=true;return bytes().buffer;}},{product:'genie',language:'en',isCurrent:()=>false});assert.equal(r.status,'cancelled');assert.equal(e.controller.state().phase,'cancelled');assert.equal(read,false);assert.equal(e.drafts.get('genie'),'Original');});
