graph TD
    n-docs-71ab8b["docs\ndocs"]
    n-examples-99345c["examples\nexamples"]
    n-package-json-7030d0["package.json\npackage.json"]
    n-public-61c9b2["public\npublic"]
    n-scripts-16728d["scripts\nscripts"]
    n-src-f27fed["src\nsrc"]
    n-tests-04d13f["tests\ntests"]
    n-worker-js-2d8aad["worker.js\nworker.js"]
