#!/usr/bin/env python3
"""Localize the Genie Orbit poster caption for the English pages.

This is an asset generator, not part of `npm run build`. It takes the original
imported poster frame and replaces ONLY the burned-in Japanese caption with the
English wording already used on the English site. Nothing else in the frame is
touched: the artifact, the Genie badge and the MAC -> IDEA -> PLAY marker are
the original pixels.

The recording itself still carries Japanese title cards and a Japanese app UI.
That is stated on the page; this poster does not pretend otherwise.

Requires Pillow. Run from the repository root:

    python3 scripts/make-poster-en.py

It rewrites public/media/derived/genie/orbit-poster-en.jpg and refreshes
public/media/derived/manifest.json, which records the source hash so the
derived file can always be traced back to the original frame.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'public/media/originals/genie/assets/genie-orbit-poster.jpg'
TARGET = ROOT / 'public/media/derived/genie/orbit-poster-en.jpg'
MANIFEST = ROOT / 'public/media/derived/manifest.json'

# Measured from the source frame, not guessed: the caption occupies these rows,
# and the subtitle sits on a faint translucent plate.
CAPTION_TOP, CAPTION_BOTTOM = 900, 1058
PLATE = (600, 960, 1320, 1051)
PLATE_LIFT = (1, 2, 2)
CLEAN_SAMPLE = range(40, 400, 4)

TITLE = 'That sketch? It moves.'
SUBTITLE = 'HTML generated by Genie / an artifact you can open'
TITLE_CENTER, SUBTITLE_CENTER = 931, 1000
FONT = '/System/Library/Fonts/HelveticaNeue.ttc'
MEDIUM, REGULAR = 10, 0


def row_background(pixels, y):
    """The frame is a flat starfield here, so a row median is an exact repair."""
    samples = sorted(pixels[x, y] for x in CLEAN_SAMPLE)
    return samples[len(samples) // 2]


def centered(draw, text, font, center_y, fill):
    left, top, right, bottom = draw.textbbox((0, 0), text, font=font)
    draw.text((960 - (right - left) / 2 - left, center_y - (bottom - top) / 2 - top), text, font=font, fill=fill)


def build() -> None:
    image = Image.open(SOURCE).convert('RGB')
    width, _ = image.size
    pixels = image.load()

    for y in range(CAPTION_TOP, CAPTION_BOTTOM + 1):
        background = row_background(pixels, y)
        plate = tuple(min(255, background[i] + PLATE_LIFT[i]) for i in range(3))
        inside_plate = PLATE[1] <= y <= PLATE[3]
        for x in range(width):
            pixels[x, y] = plate if inside_plate and PLATE[0] <= x <= PLATE[2] else background

    draw = ImageDraw.Draw(image)
    centered(draw, TITLE, ImageFont.truetype(FONT, 58, index=MEDIUM), TITLE_CENTER, (255, 255, 255))
    centered(draw, SUBTITLE, ImageFont.truetype(FONT, 29, index=REGULAR), SUBTITLE_CENTER, (226, 229, 230))

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    image.save(TARGET, 'JPEG', quality=86, optimize=True, progressive=True)

    source_bytes, target_bytes = SOURCE.read_bytes(), TARGET.read_bytes()
    MANIFEST.write_text(json.dumps({
        'schema': 1,
        'note': 'Derived from imported originals. Each entry keeps the source hash so the change stays traceable.',
        'files': [{
            'path': '/media/derived/genie/orbit-poster-en.jpg',
            'bytes': len(target_bytes),
            'sha256': hashlib.sha256(target_bytes).hexdigest(),
            'source': '/media/originals/genie/assets/genie-orbit-poster.jpg',
            'sourceSha256': hashlib.sha256(source_bytes).hexdigest(),
            'change': 'Burned-in Japanese caption replaced with the English caption used on the English pages. The frame is otherwise unmodified.',
            'generator': 'scripts/make-poster-en.py',
        }],
    }, ensure_ascii=False, indent=2) + '\n')
    print(f'Wrote {TARGET.relative_to(ROOT)} ({len(target_bytes)} bytes)')


if __name__ == '__main__':
    build()
