export const copy = {
 ja: {
  nav: ['プロダクト','企業向け支援','開発記録','ラボについて'],
  contact: '開発を相談する', menu: 'メニュー', close: '閉じる',
  tagline: 'できることの、<br>その先をつくる。',
  heroLabel: 'INDEPENDENT AI PRODUCT LAB',
  heroText: 'まだないAI体験を、自らつくる。<br>その実装力を、人と企業の「できる」へ。',
  heroPrimary: 'プロダクトを見る', heroSecondary: '共同開発を相談する',
  heroCaption: 'Reach / made — 可能性と実物のあいだ。',
  statement: '可能性について語るより、<br>触れられるものを。',
  statementText: '自然に話す。仕事を進める。結果を確かめる。<br>新しいAIの使い方を、プロダクトで探っています。',
  selectedLabel: 'SELECTED PRODUCTS', selectedTitle: '実物から、はじめる。',
  selectedText: '自主開発しているプロダクトです。顧客への導入実績とは区別し、できることと検証中のことを公開しています。',
  allProducts: 'プロダクトをすべて見る',
  productLabel: 'プロダクト案内', productSite: '製品サイト', realDemo: '実際のデモを開く', source: 'ソースと仕様',
  proof: '確認できるもの', limits: '現在の範囲', inquiry: 'この技術について相談する',
  evidence: '検証記録を読む',
  supportEyebrow:'WORK WITH REACHMADE', supportTitle:'ひとつの業務から、<br>一緒に変えていく。',
  supportText:'試して終わりにしないために、最初に何を確かめるかを決める。設計・試作・評価から、必要な連携の実装まで支援します。',
  servicesLink:'支援内容と進め方を見る',
  philosophy:'設計に残す、三つの約束。',
  principles:[['実物で話す。','自主開発のプロダクト、コード、実行記録。言葉だけでなく、確認できるものを見せます。'],['結果を確かめる。','AIの「できました」を、成功の証拠にしない。実行と確認を分け、未完了も残します。'],['使う人に決定権を。','外部への送信、費用、権限、人の承認。使う人が判断できるよう、設計に組み込みます。']],
  footerCTA:'その「できたら」を、<br>一緒につくりませんか。',
  footerText:'構想が固まる前の段階から。対象の業務と、試してみたいことを聞かせてください。',
  footerBrand:'AIの応用研究・プロダクト開発',
  footerNote:'自主開発から、企業との共同開発へ。',
  privacy:'プライバシー', external:'外部サイト', back:'トップへ戻る',
  productsTitle:'自主開発プロダクト。<br>ひとつの問い。',
  productsLead:'AIで、人が実現できることをどこまで広げられるか。<br>仕事、対話、電話、調査、協働、制作。それぞれの入口から探っています。',
  productNotice:'以下は自主開発プロダクトの紹介です。掲載機能は各公開READMEに基づき、本サイトの制作時に実アプリの再検証はしていません。',
  filters:[['all','すべて'],['work','仕事・協働'],['voice','会話・電話'],['trust','調査'],['creation','制作']],
  countSuffix:'件のプロダクト',
  servicesTitle:'AIを、現場で<br>使えるかたちへ。',
  servicesLead:'何をAIに任せるか。何を人が判断するか。<br>業務と制約を理解するところから、開発者が直接向き合います。',
  serviceIntro:'研修や提案だけで終わらせず、ひとつの業務を選び、動くものを作って確かめる。FDE（現場に入り、開発まで担うエンジニア）型の支援です。',
  serviceCards:[
   ['01','業務AI・エージェント実装','調査、下書き、レビュー、承認。人とAIの分担を設計し、結果を追える業務フローを試作します。','業務フロー / 試作 / 評価項目 / 連携仕様','Genie · Agent Team'],
   ['02','音声・電話AIの開発','対話型の練習、音声入力、電話業務。自然さだけでなく、誤認識・同意・人への引き継ぎまで設計します。','会話設計 / 音声試作 / 遅延・失敗時の評価','AI Meeting · Oathra'],
   ['03','新しいAIプロダクトの試作','まだ言葉だけのアイデアを、操作できる試作へ。使い勝手と成立条件を確かめ、次に作る範囲を整理します。','操作できる試作 / UX / 検証記録 / 次の開発範囲','複数プロダクトの自主開発経験']
  ],
  deliverables:'主な成果物', related:'関連する自主開発',
  processTitle:'小さく作り、判断できるところまで。',
  process:[['理解する','対象業務、既存システム、データ、予算、制約を整理します。'],['確かめ方を決める','成功条件、失敗条件、人が確認する場面を決めます。'],['作って試す','試作を現場の例で動かし、品質・費用・使い勝手を確かめます。'],['次の範囲を決める','限定導入や連携へ進むか、条件を見直すかを判断します。']],
  scopeTitle:'最初に、引き受ける範囲を明確にします。',
  scopeText:'費用・期間・納品物は、要件を確認してから個別に合意します。製品デモの公開は、本番導入への適合やSLAの保証ではありません。顧客データを扱う前に、送信先、権限、保持・削除、第三者サービスの条件を確認します。',
  faq:[['AI導入のテーマが決まっていなくても相談できますか？','はい。時間がかかっている業務や、実現したい体験から整理します。AIを使う必要があるかも含めて検討します。'],['PoCから本番まで、すべて任せられますか？','対応する工程と運用体制は個別に合意します。認証・監視・復旧・保守など、本番に必要な条件を整理した上で判断します。未検証の製品をそのまま本番用として納品する前提ではありません。'],['既存のAI・DX会社との協業はできますか？','顧客向け案件の実装パートナーとしての相談も受け付けます。対象技術、役割分担、コードの権利、データの扱いを確認します。'],['公開コードはすべて同じライセンスですか？','いいえ。製品ごとに異なり、素材やモデルには別条件があります。Genieは現在、全体のOSSライセンスが未設定です。導入前に対象範囲を確認します。']],
  workTitle:'作ったこと。<br>確かめたこと。',
  workLead:'成果物だけでなく、そこまでの判断も。<br>自主開発で公開しているデモと検証記録を、入口ごとにまとめました。',
  workNote:'このページは公開資料への案内です。顧客案件の実績や、第三者監査の結果ではありません。最新の条件・詳細はリンク先で確認できます。',
  readSource:'公開README', recordedDemo:'録画・操作デモ',
  aboutTitle:'考えて、作って、<br>その先まで。',
  aboutLead:'Reachmade Labは、AIの応用研究とプロダクト開発に取り組む、独立した開発活動のブランドです。',
  aboutBody:'実現したいことと、今できること。その間にある距離を、技術で少しずつ縮めたい。自然な会話から、仕事を進めるエージェントまで、実際に触れられるものを作りながら探究しています。',
  aboutBody2:'自主開発で得た知見は、企業の業務や新規事業にも。相談する人と作る人を分けず、設計・実装・評価に直接向き合う形を大切にしています。',
  ownerRole:'開発者 / FORIFOR', ownerName:'Shuhei Horio',
  ownerText:'Genie、AI Meeting、Oathra、AI Secure、Agent Team、Launchloomを開発。コードや設計、検証記録をGitHubで公開しています。',
  identity:'Reachは「手が届く範囲」、madeは「形になったもの」。人と企業が実現できることを、実物を作ることで広げていく名前です。',
  aboutNotice:'自主開発プロダクトと、顧客向けの導入実績は分けて扱います。法人・研究機関との提携や、未取得の認証を示すものではありません。',
  contactTitle:'その構想を、<br>聞かせてください。',
  contactLead:'ひとつの業務でも、まだ輪郭のないアイデアでも。<br>技術で何ができるか、一緒に整理するところから始めます。',
  contactPrimary:'非公開の相談フォームを開く',
  contactNote:'現在は開発者の既存窓口（AI Meetingのサイト内）に移動します。Reachmade専用メール・直接送信フォームは未設定です。送信先と取り扱いをリンク先でご確認ください。',
  draftTitle:'相談の下書きを、ここで。',
  draftNote:'この入力はブラウザ内だけで処理し、サーバーに送信・保存しません。コピーして、相談フォームに貼り付けて使えます。',
  topicLabel:'相談したいこと', detailLabel:'対象業務・実現したいこと', timingLabel:'時期・現在の状況（任意）',
  detailPlaceholder:'例：問い合わせ対応の一部を音声AIで試したい。対象は予約変更で、最終確定はスタッフが行う想定です。',
  draftButton:'相談文をコピー', draftWarning:'機密情報・顧客の個人情報・認証情報は入力しないでください。送信済みにはなりません。',
  githubNote:'不具合や非機密の技術的な話は、各製品のGitHubへ。',
  privacyTitle:'プライバシーについて',
  privacySections:[['このサイトでの入力','相談文の下書きはブラウザ内でのみ処理されます。本サイトには送信APIやデータベースを設けておらず、下書きをサーバーへ送信・保存しません。コピーは利用者の操作で行います。'],['外部の相談窓口・デモ','相談フォーム、動画、GitHubなどは外部リンクです。開いた先のサービスが情報を取り扱います。入力・送信前に、各サービスの方針と送信先をご確認ください。'],['解析と外部アセット','配布時点のサイトコードには広告タグ、アクセス解析タグ、外部フォント、動画埋め込みを入れていません。デモはリンクを押したときに外部サイトで開きます。Cloudflare等のホスティング事業者は配信・セキュリティのため接続情報を処理する場合があります。'],['設定を変更するとき','専用の相談フォームや解析ツールを導入する際は、送信先、利用目的、保存期間、削除窓口などを定め、このページを更新してから公開します。'],['運営者','Reachmade Lab / Shuhei Horio（FORIFOR）。お問い合わせは相談ページから、現在案内している外部窓口へ進んでください。']],
  notFound:'このページは見つかりませんでした。', notFoundBody:'URLが変わったか、まだ公開されていないページです。プロダクトと企業向け支援はトップページからご覧ください。'
 },
 en: {
  nav:['Products','For companies','Work notes','About the lab'], contact:'Work with us', menu:'Menu', close:'Close',
  tagline:'Make room<br>for possible.', heroLabel:'INDEPENDENT AI PRODUCT LAB',
  heroText:'We build new AI experiences.<br>Then bring that engineering to people and businesses.', heroPrimary:'Explore the products', heroSecondary:'Discuss a project', heroCaption:'Reach / made — between possibility and something real.',
  statement:'Less talk about possibility.<br>More things you can try.', statementText:'Talk naturally. Move work forward. Inspect the result.<br>We explore what AI can do by building products.',
  selectedLabel:'SELECTED PRODUCTS', selectedTitle:'Start with something real.', selectedText:'Independently developed products, not client deployment claims. Each has its own capabilities, conditions, and open questions.', allProducts:'Explore all products',
  productLabel:'Product guide', productSite:'Product site', realDemo:'Open the real demo', source:'Source & documentation', proof:'What you can inspect', limits:'Current scope', inquiry:'Discuss this technology', evidence:'Read the evaluation',
  supportEyebrow:'WORK WITH REACHMADE',supportTitle:'One workflow.<br>A useful place to start.',supportText:'Before building a prototype, decide what it needs to prove. We support design, implementation, evaluation, and the integrations a workflow needs.',servicesLink:'Explore how we work',
  philosophy:'Three things we build around.', principles:[['Show the work.','Products, code, and execution records. Something inspectable, not just a claim.'],['Check the result.','An agent saying “done” is not proof. Separate execution from verification, and preserve what is incomplete.'],['Keep people in control.','Data destinations, cost, permissions, and approvals should be things people can understand and decide.']],
  footerCTA:'What would you like<br>to make possible?',footerText:'An unfinished idea is a good place to start. Tell us about the work, and what you want to try.',footerBrand:'Applied AI research & product development',footerNote:'From independent products to collaborative development.',privacy:'Privacy',external:'External site',back:'Back to home',
  productsTitle:'Independent products.<br>One question.',productsLead:'How much further can AI help people reach?<br>Work, conversation, calls, investigation, collaboration, and creation.',productNotice:'These are independently developed products. Descriptions follow their public READMEs; the applications were not re-tested as part of building this website.',
  filters:[['all','All'],['work','Work & agents'],['voice','Voice & calls'],['trust','Investigation'],['creation','Creation']],countSuffix:'products',
  servicesTitle:'AI that fits<br>the work.',servicesLead:'What should AI do? What should people decide?<br>We start with the workflow, the existing systems, and the constraints.',serviceIntro:'Not just a workshop or a recommendation. Choose one workflow, make a working prototype, and evaluate it. A forward-deployed approach: the engineer who understands the work also builds the system.',
  serviceCards:[['01','Workflow AI & agents','Design how people and AI share research, drafting, review, and approval. Prototype workflows with results you can trace.','Workflow map / prototype / evaluation / integration design','Genie · Agent Team'],['02','Voice & phone AI','Prototype training conversations, voice input, or phone workflows. Include misrecognition, consent, and human handoff in the design.','Conversation design / voice prototype / latency and failure evaluation','AI Meeting · Oathra'],['03','New AI product prototypes','Turn an idea into something people can use. Test the experience and its assumptions before deciding what to build next.','Working prototype / UX / evaluation record / next-stage scope','Experience across independent products']],
  deliverables:'Typical deliverables',related:'Related independent work',processTitle:'Build small. Learn enough to decide.',process:[['Understand','Map the workflow, existing systems, data, budget, and constraints.'],['Define the test','Agree on success, failure, and where people need to review a result.'],['Build & evaluate','Run a prototype against representative examples. Examine quality, cost, and usability.'],['Choose the next step','Decide whether to proceed to a limited deployment, add integrations, or revise the approach.']],
  scopeTitle:'Agree on the scope before making a promise.',scopeText:'Fees, timing, and deliverables are agreed after reviewing the requirements. A public demo is not a production guarantee or an SLA. Data destinations, permissions, retention, deletion, and third-party terms are reviewed before using customer data.',
  faq:[['Can we talk before choosing an AI use case?','Yes. Start with a time-consuming workflow or an experience you want to make. Whether AI is appropriate is part of the discussion.'],['Do you handle everything from a prototype to production?','The stages and operational responsibilities are agreed individually. Authentication, monitoring, recovery, and support requirements come before production acceptance. An unverified prototype is not delivered as production-ready.'],['Do you work with other AI and DX firms?','Implementation partnerships are welcome. We clarify the technology, division of work, code rights, and data handling.'],['Do all products have the same open-source license?','No. Licenses vary and assets or models may have separate conditions. Genie currently has no project-wide open-source license. Reuse needs a product-specific review.']],
  workTitle:'What was built.<br>What was checked.',workLead:'Not just the output, but the decisions behind it.<br>A guide to demos and evaluation records from independent development.',workNote:'These links describe independent work, not customer deployment case studies or third-party audits. See the source for the latest scope and conditions.',readSource:'Public README',recordedDemo:'Recording / interactive demo',
  aboutTitle:'Think it through.<br>Then make it real.',aboutLead:'Reachmade Lab is an independent development brand exploring applied AI and new product experiences.',aboutBody:'There is a gap between what people want to do and what they can do today. We want to close that gap by building: from natural conversation to agents that move work forward.',aboutBody2:'What we learn in independent development also informs work with companies. The person discussing the problem is directly involved in designing, building, and evaluating the solution.',ownerRole:'Developer / FORIFOR',ownerName:'Shuhei Horio',ownerText:'Developing Genie, AI Meeting, Oathra, AI Secure, Agent Team, and Launchloom. Code, design notes, and evaluation records are published on GitHub.',identity:'Reach is what is within your grasp. Made is something that exists. Reachmade is about extending what people and businesses can do, by making something real.',aboutNotice:'Independent products and client deployment experience are kept separate. The brand does not imply institutional affiliation or unearned certifications.',
  contactTitle:'Tell us what<br>you have in mind.',contactLead:'One workflow, or an idea that is not quite formed.<br>Start with what you want to make possible.',contactPrimary:'Open the private inquiry form',contactNote:'This currently opens the developer’s existing inquiry route on the AI Meeting site. A dedicated Reachmade mailbox and direct form are not configured. Review the destination and its terms before submitting.',draftTitle:'Start a brief here.',draftNote:'This draft is processed only in your browser. It is not sent to or saved on a server. Copy it into the inquiry form when you are ready.',topicLabel:'What is the project about?',detailLabel:'The workflow or idea',timingLabel:'Timing and current stage (optional)',detailPlaceholder:'Example: try voice AI for reservation changes. Staff would make the final confirmation.',draftButton:'Copy the project brief',draftWarning:'Do not include confidential information, customer data, or credentials. Copying is not submission.',githubNote:'For bugs and non-confidential technical questions, use the relevant product repository.',
  privacyTitle:'Privacy',privacySections:[['Drafts on this site','The project brief is processed only in your browser. This site has no submission API or database and does not send or store that draft on a server. Copying requires your action.'],['External forms and demos','Inquiry forms, videos, and GitHub are external links. Information is handled by the destination service after you visit it. Check that service’s terms before entering or sending information.'],['Analytics and assets','The shipped website code includes no advertising or analytics tags, external fonts, or embedded video. Demo links open an external site only when selected. Hosting providers such as Cloudflare may process connection information for delivery and security.'],['Future changes','Before adding a direct form or analytics, define the destination, purpose, retention, and deletion contact, and update this page.'],['Operator','Reachmade Lab / Shuhei Horio (FORIFOR). The contact page links to the currently available external inquiry route.']],
  notFound:'This page could not be found.',notFoundBody:'The address may have changed, or the page is not published yet. Explore the products and company services from the home page.'
 }
};
