import fs from 'node:fs/promises';
import path from 'node:path';
export function renderInquiry(language) {
  const ja=language==='ja';
  if (!['ja','en'].includes(language)) throw new TypeError('Unknown language');
  const t=(a,b)=>ja?a:b;
  return `<section class="page-intro container"><p class="eyebrow">LET’S MAKE SOMETHING</p><h1>${t('どんな仕事を、変えたいですか。','What would you like to change?')}</h1><p class="lead">${t('まだ仕様がなくても大丈夫です。課題や試してみたいことから、相談してください。','Start with the problem or an experience you would like to try. A finished specification is not required.')}</p></section>
<section class="container inquiry-layout"><aside class="inquiry-context"><h2>${t('このページから、相談できます。','Send your inquiry here.')}</h2><p>${t('開発・導入・カスタマイズなど、ご相談の内容をお送りください。受付番号は保存が完了した後に表示します。','Send a question about development, integration or customization. A receipt appears only after your inquiry has been stored.')}</p><p>${t('AIへ入力内容を送信しません。添付ファイルや機密情報は、最初の相談には不要です。','The form does not send your message to an AI. Attachments and confidential information are not needed for the initial conversation.')}</p><a class="text-link" href="https://ai-meeting.forifor.chatgpt.site/${ja?'ja':''}#business" target="_blank" rel="noopener noreferrer">${t('接続できない場合は既存の窓口へ','Use the existing form when unavailable')} ↗</a></aside>
<form id="reachmade-inquiry" class="inquiry-form" method="post" action="/api/inquiries" aria-describedby="inquiry-privacy" data-language="${language}"><fieldset><legend class="sr-only">${t('ご相談の内容','Inquiry details')}</legend><div class="inquiry-fields"><label>${t('お名前','Name')}<input name="name" autocomplete="name" required maxlength="80"></label><label>${t('返信先メール','Reply email')}<input name="email" type="email" autocomplete="email" required maxlength="254"></label><label>${t('会社・組織名（任意）','Organization (optional)')}<input name="organization" autocomplete="organization" maxlength="120"></label><label>${t('相談の対象','Topic')}<select name="useCase"><option value="custom">${t('まだ決まっていない・共同開発','General / collaboration')}</option><option value="genie">Genie</option><option value="tasks">AI Meeting</option><option value="oathra">Oathra</option><option value="aisecure">AI Secure</option><option value="agent-team">Agent Team</option><option value="launchloom">Launchloom</option></select></label><label class="inquiry-wide">${t('相談したいこと','Your inquiry')}<textarea name="message" rows="6" required minlength="10" maxlength="2000" aria-describedby="inquiry-help"></textarea><small id="inquiry-help">${t('10〜2,000文字。パスワード・APIキー・顧客の個人情報は記載しないでください。','10–2,000 characters. Do not include passwords, API keys or private customer information.')}</small></label></div><label class="inquiry-trap" aria-hidden="true">Website<input name="website" autocomplete="off" tabindex="-1"></label><label class="inquiry-consent"><input name="consent" type="checkbox" required><span>${t('入力した内容を、Reachmade運営者のGoogle Cloud受付システムへ送信・保存することに同意します。','I agree to send and store these details in the Reachmade operator’s Google Cloud inquiry system.')}</span></label><p id="inquiry-privacy">${t('送信ボタンを押すまで、入力内容は送信しません。受付後は運営者が対応のために確認します。自動返信メールは送信されません。','Your input is not transmitted until you press Send. The operator reviews accepted inquiries for follow-up. No automatic confirmation email is sent.')} <a href="${ja?'':'/en'}/privacy/">${t('情報の取り扱い','Privacy information')}</a></p><button id="inquiry-submit" class="button" type="submit" disabled>${t('相談を送る','Send inquiry')} →</button></fieldset><div class="inquiry-connection"><span id="inquiry-readiness" role="status">${t('受付への接続を確認しています。','Checking the inquiry connection.')}</span><button id="inquiry-reconnect" type="button">${t('接続を再確認','Check again')}</button></div><p id="inquiry-result" role="status" aria-live="polite" aria-atomic="true" tabindex="-1"></p><noscript>${t('送信にはJavaScriptが必要です。既存の窓口からご相談ください。','JavaScript is required to send. Please use the existing form linked here.')}</noscript></form></section>`;
}
export async function writeInquiryPages(dist) {
  for (const language of ['ja','en']) {
    const file=path.join(dist,language==='ja'?'contact/index.html':'en/contact/index.html');
    const source=await fs.readFile(file,'utf8');
    if ((source.match(/<main id="main">/g)||[]).length!==1 || (source.match(/<\/main>/g)||[]).length!==1 || !source.includes('src="/assets/site.js"')) throw new Error('Contact page structure changed');
    const html=source.replace(/(<main id="main">)[\s\S]*?(<\/main>)/,(_,a,b)=>a+renderInquiry(language)+b)
      .replace('src="/assets/site.js"','type="module" src="/assets/inquiry-form.mjs"')
      .replace('</head>','<link rel="stylesheet" href="/assets/inquiry-form.css"></head>');
    await fs.writeFile(file,html);
  }
}
